client/package.json
client/src/App.js
client/src/App.test.js
client/src/Dashboard/__tests__/Dashboard.test.js
client/src/Login/Login.js
client/src/Login/__tests__/Login.test.js
client/yarn.lock

Adds `react-ga` package to the front-end client, and adds a login page pageview event for testing
Closes #10 Add Google Analytics
We want to re-implement the places Analytics is being called currently (all in the old UI), via react
- `cd client && yarn install`
- fire up the app
- visit /login
- visit Google Analytics, you should see an active user and an event with the Category "Guest" and the Action "Landed on Login Page"
I'm not sure how to separate localhost from deployed environments, I'll make a ticket for that.

Adds google analytics, and moves tests to their own directories

---

client/src/App.js
client/src/Login/Login.js
client/src/Login/__tests__/Login.test.js

Does it what it says on the tin 🙂

Move side effects into effects and enable GA only in Production

---

.github/workflows/ci.yml
app/controllers/api/v1/users_controller.rb
app/models/child.rb
app/models/user.rb
db/migrate/20200425210517_add_organization_to_user.rb
db/schema.rb
spec/factories/children.rb
spec/factories/users.rb
spec/models/child_spec.rb
spec/models/user_spec.rb
spec/requests/api/v1/businesses_spec.rb
spec/requests/api/v1/children_spec.rb
spec/requests/api/v1/users_spec.rb
spec/support/api/schemas/user.json
spec/support/api/schemas/user_with_businesses.json
spec/support/api/schemas/user_with_children.json
spec/support/api/schemas/users.json
spec/swagger_helper.rb
swagger/v1/swagger.json

Fixes #78 
Adds an organization field to the User table
The user should be able to name the organization they work for, since it might be different from the businesses they are overseeing.
`rails db:migrate:with_data`
Organization should now be required on the User create endpoint; also organization was added to the user_with_children and user_with_businesses json response definitions (though we don't have an endpoint for those currently)
None!

Add organization to user

---

app/controllers/api/v1/children_controller.rb
app/models/child.rb
db/migrate/20200426002926_remove_first_and_last_name_from_children.rb
db/schema.rb
spec/factories/children.rb
spec/models/child_spec.rb
spec/requests/api/v1/children_spec.rb
spec/support/api/schemas/child.json
spec/support/api/schemas/children.json
spec/support/api/schemas/user_with_children.json
spec/swagger_helper.rb
swagger/v1/swagger.json

Fixes #51 - removes the first and last name columns from the children table; we're going to take in first and last name and save it as full_name.  The intention is never to update CCMS info from our API; instead we'll be associated to children via ccms_id and pass data from Pie that is unique (regarding subsidy status, etc).  We want to be inclusive; some folks don't have a first and a last name.
```
rails db:migrate:with_data
```
- Make sure API requests with no first_name or last_name still pass.
- Make sure API requests with first_name and last_name still pass; they should just ignore those fields.

Removes first and last name from children table

---

client/src/_assets/styles/layouts/signup.css

Fixes [125](https://github.com/pieforproviders/pieforproviders/issues/125) Image was fixed and set to width/length auto which meant that for larger screens, the element would contain white space once the width of the image had been fulfilled. Image is now always set to 100% width and with a local background-attachment which means that it will scroll and resize on width depending on the screen size.
_No, no tests were written before as this was a css change, but I'd be happy to do so!_
_Not necessary_
_None of the above_
Run locally, show on many screens
From my 13 inch Macbook:
From my larger (how many inches?) display:

Responsive Signup media

---

client/src/Signup/Signup.js

Fixes [131](https://github.com/pieforproviders/pieforproviders/issues/131) Was mb-4 distance between phone number label and form but now its mb-2. Ta-da!

shortened space between label and form

---

docs/dbdiagram.dbml

We needed to be able to filter the user's list of agencies by the state they're in, initially.

Added state to agencies

---

app/models/business.rb
app/models/child.rb
app/models/user.rb
app/models/uuid_application_record.rb

#168 Parent abstract class for ActiveRecord models with UUID 'created_on' 
1. Added `class UuidApplicationRecord < ApplicationRecord` 
It has the common bit of code that all AR models using UUID need so that ordering (.first, .last) works properly.
2. Changed existing ActiveRecord models to inherit from this new class and removed the duplicated code.
_(none)_
All new AR models (with UUIDs) will need to inherit from this class instead of ApplicationRecord.  [just a reminder]
I'm happy to use a different name for the class.  This is just made sense to me.

#168: Add an abstract class for all ActiveRecords using UUID so ordering is correct for all

---

client/src/Signup/Signup.js

When a user tries to sign up with an existing email address, an _Email has already been taken_ error message is displayed. Previously, the request failed silently and no feedback was given.
**Screenshot**
1. Try to sign up with an existing email address (test@test.com)
2. The _Email has already been taken_ error message should be displayed

Display an error message if the email address is already taken

---

client/src/App.js
client/src/_shared/AuthLayout.js

Fixes https://github.com/pieforproviders/pieforproviders/issues/156
When you go to http://localhost:3000, the `AuthLayout` component renders the `Login` component by calling the function (i.e. `rightColumnContent()`) and a few hooks from the `Login` component are rendered. If you click on the **SIGN UP** link, the `Signup` function is called and it uses more hooks than the `Login` component. This is the reason for the `Rendered more hooks than during the previous render` error.
When you go to http://localhost:3000/signup, the hooks from the `Signup` component will be rendered the first time. If you click on the **LOG IN** link, there'll be fewer hooks rendered and you'll run into the `Rendered fewer hooks than expected. This may be caused by an accidental early return statement` error. …

Fix "Rendered more hooks than during the previous render" error

---

client/src/App.js
client/src/_utils/index.js

After logging in, if the user tries to go `/`, they are redirected to `/login` even when they are already logged in. This PR fixes it by redirecting the user to the dashboard instead.
1. Get the app up and running and log in
2. Go to `/`. You should be redirected to `/dashboard`
The `isUserLoggedIn` function just checks for the presence of `pie-token` from the local storage as done [here](https://github.com/pieforproviders/pieforproviders/blob/develop/client/src/_utils/_routes/AuthorizedRoute.js#L14). I am not sure if this is fine to ensure a user is logged in though.

Redirect the user to the dashboard if logged in

---

spec/requests/api/v1/businesses_spec.rb
spec/requests/api/v1/sites_spec.rb
spec/support/shared_examples_api_request.rb

#179 DRY API Specs  Use RSpec.shared_examples for the common API requests for Rails models.  Pass parameters to the shared_examples as needed to specify names, classes, data to be updated, etc.
The shared examples show how much duplication there is in the specs.  Just the names of the classes (and the data to change with the `update` action) vary.  I am passing in the lower case 'item name,' but we could do away with that, since it's based on the class name.
This PR is here so it can be discussed/reviewed. 
There are likely things that can be further refactored/cleaned up/improved; I wanted to get this pushed so we can at least think about it and discuss.
I'm not happy with the names of the shared examples, but those can be changed later.

#179 RSpec.shared_examples for Rails model API actions

---

spec/requests/api/v1/payments_spec.rb
spec/requests/api/v1/sites_spec.rb
spec/support/api/schemas/agencies.json
spec/support/api/schemas/agency.json
spec/support/api/schemas/businesses.json
spec/support/api/schemas/children.json
spec/support/api/schemas/site.json
spec/support/api/schemas/sites.json
spec/support/api/schemas/user.json
spec/support/api/schemas/user_with_businesses.json
spec/support/api/schemas/user_with_children.json
spec/support/api/schemas/users.json
spec/swagger_helper.rb
swagger/v1/swagger.json

fixes #198 
I added "active" as a required parameter to both `agency.json` and `site.json`.  Previously, the plurals of those (`agencies.json` and `sites.json`) had "active" as required, but the singular versions did not.  (IOW: discrepancy).
I spent waaaay too many hours trying to figure out a reasonable way to have the definitions in  `swagger_helper`  refer to the `.json` files in `spec/support/api/schemas'.  But couldn't make it happen.  (That way we'd only have 1 schema defined for each model, instead of having it defined once in a .json file _and_ in swagger_helper.rb.)
At least now I have a deep understanding of what rswag is doing.

DRY json spec schemas and swagger_helper

---

app/models/child_site.rb
app/models/site.rb

Removes the `implicit_order_column` setting from `Site` and `ChildSite` models by inheriting from `UuidApplicationRecord`.

Inherit Site and ChildSite models from UuidApplicationRecord

---

client/src/Signup/Signup.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

- Only sets validation errors if the response status is 422
- Introduces a new state for non-validation errors to capture 500 responses from the server and displays a generic error message.
- Resets the error state before submitting the form
Sign up with an existing phone number or email and you should find the error message show up.

Improve signup error handling

---

config/application.rb
config/environments/development.rb

Moves development environment-specific config from `config/application` to `config/environments/application.rb`

Move development-specific config from application config

---

client/src/_shared/LoggedInLayout.js

When the user clicks on the **Log Out** link, the token in `localStorage` is removed and the user is redirected to `/login`.
1. Log in.
2. Click on the **Log Out** link on the top right. You should be taken back to `/login`.

Allow users to log out

---

client/src/App.js
client/src/CasesImport/CasesImport.js
client/src/CasesImport/CasesImportReview.js
client/src/CasesImport/utils.js
client/src/Dashboard/Dashboard.js
client/src/ErrorBoundary/ErrorBoundary.js
client/src/ErrorBoundary/index.js
client/src/GettingStarted/GettingStarted.js
client/src/Login/Login.js
client/src/NotFound.js
client/src/Signup/Confirmation.js
client/src/i18n/index.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

#23 #251
Replaces all hard-coded English copy with `t('key')` to support both English and Spanish.
Visit all the pages and switch the language (you can update the language in `localStorage` — `localStorage.setItem('i18nextLng', 'es')` or use the language switcher on the login and signup pages).

Internationalize pages

---

client/src/Signup/Signup.js

https://github.com/pieforproviders/pieforproviders/issues/249
Passes a custom validator function in the rule object to make sure the service agreement checkbox is checked.
1. Go to the signup form and fill all the details except the service agreement checkbox
2. Click the **SIGN UP** button. You should find the _Please read and agree to our Terms of Service_ message.
3. Check the checkbox and uncheck it again. You should find the error message again.

Fix service agreement checkbox validation on the Signup form

---

app/models/user.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/registrations_spec.rb

Previously, a user was able to sign up without accepting the service agreement. This PR fixes the validation of the `service_agreement_accepted` field in the API to make sure it is `true`.
The frontend validation is handled in #261.

Fix service agreement acceptance validation in the User model

---

.github/workflows/ci.yml

From the discussion on Slack, we have decided to only run the Cypress E2E tests on pushes and pull requests to the main branch.

Only run E2E tests on pushes and PRs to the main branch

---

app/models/user.rb
db/migrate/20200902182940_add_not_null_constraint_to_users_greeting_name.rb
db/structure.sql
spec/factories/users.rb
spec/models/user_spec.rb

The greeting name has a presence validation in the frontend but the table lacks it. This PR adds a not-null constraint to `users.greeting_name` and adds a model validation.
Run `rails db:migrate`

Add not null constraint to users' greeting name

---

client/src/Login/Login.js
client/src/Signup/Signup.js
client/src/_shared/_hooks/useApiResponse.js

https://github.com/pieforproviders/pieforproviders/issues/277
We weren't sending the `Accept-Language` header to `GET /confirmation`. This PR adds the header to be sent for all requests.
1.  Sign up in English
1.  Before using the confirmation URL with a bad token, go to the login page and switch the language to Spanish
1.  Use the URL with a bad confirmation token
1.  The alert should be displayed in Spanish
Note that if you switch the language after seeing the error notification, the notification title will not be translated as it comes from the server.

Add Accept-Language header to all API requests

---

app/controllers/api/v1/users_controller.rb
client/src/GettingStarted/GettingStarted.js
client/src/GettingStarted/__tests__/GettingStarted.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
config/routes.rb
spec/requests/api/v1/users_spec.rb
swagger/v1/swagger.json

https://github.com/pieforproviders/pieforproviders/issues/281
- Replaces `/users/:slug` with /`profile` in the API and adds tests
- Displays the user's greeting name on the Getting Started page
- Updates frontend unit tests
1. Sign up and log in to the account
2. Go to `/getting-started`
3. You should find the greeting name next to 'Welcome to Pie for Providers'

Display user's greeting name on the Getting Started page

---

.dependabot/config.yml

See #299 comment - we don't want to upgrade eslint because react-scripts uses an older version and it's pinned at that version for create-react-app-generated apps

Adds dependabot config to ignore eslint

---

client/src/App.js
client/src/App.less
client/src/GettingStarted/GettingStarted.js
client/src/Login/Login.js
client/src/Signup/Signup.js
client/src/_assets/styles/customize-antd.less
client/src/_shared/AuthLayout.js
client/src/_shared/LoggedInLayout.js
client/tailwind.config.js

#238 sets breakpoints at our custom screen sizes for both tailwind and Ant Design
Change your screen to our breakpoints as laid out in the ticket, you should see the expected screens from Figma.  Our sizes will be:
```
xs: '360px',
sm: '768px',
md: '1024px',
lg: '1280px'
```
because of limitations with Ant design

Sets up breakpoints

---

lib/tasks/prep.rake

Removes `yarn heroku-postbuild` from the `prep` rake task since it is included as a part of `yarn cy:ci`.

Fix prep rake task

---

app/controllers/confirmations_controller.rb
client/src/Signup/ConfirmationSent.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
config/locales/en.yml
config/locales/es.yml
spec/cypress/app_commands/scenarios/confirm_user_account.rb
spec/cypress/integration/signup.spec.js

https://github.com/pieforproviders/pieforproviders/issues/318
If the user clicks on the **Click here to resend the email** link after confirming their email address, they are redirected to the login page and an error message is shown.
1. Sign up for an account. You should be taken to the confirmation instructions page
2. Click on the link in the confirmation email sent to your email address
3. Go back to the confirmation instructions page and click the **Click here to resend the email** link. You should be taken to the login page and the error message _You have already verified your account. You can now log in._ should show up
Note that the alert title **Confirmation Error** will not be translated upon switching the language to Spanish. This is because the message comes from the backend. …

Display an error message if the user has already confirmed their email address

---

app/controllers/application_controller.rb
client/src/Signup/Signup.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
spec/requests/registrations_spec.rb

https://github.com/pieforproviders/pieforproviders/issues/333
- Updates the error response to include the [error details](https://guides.rubyonrails.org/active_record_validations.html#validations-overview-errors-details) with the validator names (e.g. blank, taken, etc)
- Defines translations for the validator names.
1. Sign up with an email address that already exists in the database
2. You should find the message "Email has already been taken"  (if the selected language is English)
3. Switch the language to Spanish and you should find the message "Correo ya ha sido tomado"
4. Sign up with a phone number that already exists and the error message should be translatable

Move signup validation error translations to the frontend

---

.env.sample
config/database.yml

Allows a user to run Postgres 12.3 on a port different from 5432 (when there are multiple Postgres servers running on the same machine).

Add port to database configuration

---

spec/cypress/app_commands/scenarios/confirmation_token_expired.rb
spec/cypress/integration/confirmation.spec.js

https://github.com/pieforproviders/pieforproviders/issues/274
Adds an E2E test to assert an error message is displayed when a user tries to confirm their account with an expired token.

Add E2E tests for confirmations with expired tokens

---

client/craco.config.js
client/src/Login/Login.js
client/src/PasswordReset/NewPassword.js
client/src/Signup/Signup.js
client/src/_shared/ActionLink.js
client/src/_shared/AuthLayout.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
client/tailwind.config.js

#426 
Fixes a few accessibility issues:
• Missing two input labels
• Landmark / markup structure issues
• Error text color lacks sufficient contrast
• Language toggle missing focus state
Ran tests and did some manual testing.
NA
NA
Go to the sign up view and run [axe](https://www.deque.com/axe/) or [Lighthouse](https://developers.google.com/web/tools/lighthouse)
There will be some ARIA issues flagged by the tests, but I imagine it would be very hard to untangle from the Ant components (I'm not qualified). There are also three color contrast issues that are flagged - two are false and one is for a non-essential element that would require some css overrides of the Ant styles, so I left it for now.

[426] Accessibility for sign up view

---

client/src/_shared/LoggedInLayout.js

#248  💅🏼 What issue does this fix? fix nav bar responsiveness to use hamburger menu at <= 768px

check window width for navbar and hold in state to re-render as needed

---

Gemfile
Gemfile.lock

Reverts pieforproviders/pieforproviders#785 - there's currently a bug in pgreset that is preventing db resets

Revert "Bump pgreset from 0.1.1 to 0.2"

---

client/src/Dashboard/Dashboard.js
client/src/_assets/styles/dashboard-overrides.css

#677
login with both IL and NE users and confirm that a date filter button with static data showing the current month renders in the dashboard title and an 'as of' data point configured from the user data from API

configure as of figure and static date filter number and render

---

client/src/Dashboard/Dashboard.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

related to #677 -- adds translations for 'as of' and months
* [ x] Did you run `yarn lint` in `/client`?
confirm that 'As of' and months switch back and forth between english and spanish. (challenging to test currently, since the month is Feb and test data for 'as of' also uses feb, since spanish and english abbreviations for Feb are the same. may want to add a different month for 'As of' test data @katelovescode for QA purposes )

add as of and month translations

---

lib/tasks/temporary_ne_dash.rake

#965 - adds a rake task to run on staging (we had populated this data before using a data migration but were missing a status option, so this rake task will let us update and re-run dashboard data population on staging at any time
Run the rake task; your Nebraska kids should get new dash data, randomized

[965] Adds temporary ne dash rake task

---

.github/release-drafter.yml
app/blueprints/business_blueprint.rb
app/blueprints/child_blueprint.rb
app/blueprints/user_blueprint.rb
app/controllers/api/v1/users_controller.rb
app/models/child.rb
app/models/illinois_approval_amount.rb
app/models/user.rb
app/services/attendance_rate_calculator.rb
app/services/attendance_risk_calculator.rb
app/services/illinois_attendance_rate_calculator.rb
app/services/illinois_attendance_risk_calculator.rb
config/application.rb
lib/tasks/auto_annotate_models.rake
lib/tasks/prep.rake
spec/requests/api/v1/users_spec.rb

#921 this adds a `filter_date` param to the controller so it can accept a date for the dashboard to use to display data for any given month.  It involves a little renaming and refactoring of a scope on illinois_approval_amounts so we can use scopes better (using `where` rather than `find_by` which is syntactically not really a scope)
- make sure you have approvals and attendances in the date you're going to test with
- hit the `/case_list_for_dashboard` endpoint with a date formatted `YYYY-MM-DD`
- you should see the correct data for that month
**Caveat**: this will only work as expected in IL right now since NE isn't using calculations - cc @csprayregen

[929] API accepts date for dashboard

---

app/blueprints/user_blueprint.rb
app/models/user.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/support/api/schemas/illinois_case_list_for_dashboard.json
spec/support/api/schemas/nebraska_case_list_for_dashboard.json

#929 - wraps up returning the first approval date
hit /case_list_for_dashboard and the response should include a date for the first approval as `first_approval_effective_date`

Returns first_approval_effective_date

---

app/blueprints/child_blueprint.rb
app/models/user.rb
app/services/illinois_attendance_rate_calculator.rb
app/services/illinois_attendance_risk_calculator.rb
spec/blueprints/business_blueprint_spec.rb
spec/blueprints/child_blueprint_spec.rb
spec/blueprints/user_blueprint_spec.rb

Adds specs for blueprints and guard clauses for fields when no filter date is passed in
N/A - spec coverage for existing behavior
The dashboard should still display correctly

Adds specs for blueprints

---

client/src/Dashboard/DashboardTable.js

Remove 'of XX' from full days and hours columns

---

app/models/concerns/licenses.rb
db/schema.rb
spec/models/business_spec.rb
spec/models/illinois_rate_spec.rb
spec/support/api/schemas/license_types.json
spec/support/licenses_shared_examples.rb

#1271 - adds family_in_home to license types and buffs up the specs
Go to rails console and create a Business with a license_type of `family_in_home` - it should work.  Try to add a Business with a license_type of "fake type" - it should not work.

Adds family_in_home to license types and buffs up the specs

---

app/controllers/api/v1/attendances_controller.rb
app/models/attendance.rb
config/routes.rb
spec/factories/attendances.rb
spec/models/attendance_spec.rb
spec/requests/api/v1/attendance_batches_spec.rb
spec/requests/api/v1/attendances_spec.rb

Adds a GET endpoint for attendances, added a weekly scope to default the initial call to
#1332 - unblocks the attendance view
open up a Rails console:
```
$ bundle exec rails console
> require 'factory_bot_rails'
=> false
> FactoryBot.create_list(:attendance, 3, check_in: Faker::Time.between(from: Time.current.at_beginning_of_week, to: Time.current))
```
This will create three attendances this week.  In Postman, log in as an admin, and hit `/api/v1/attendances` with no filter_date.  You should see all 3 attendances you created.
If you want to test specific users' views, you can do this:
```
$ bundle exec rails console
> require 'factory_bot_rails'
=> false
> child = FactoryBot.create(:child, business: Business.find_by(user: User.find_by(email: "test@test.com")))
> …
```

[PIE-1332] Adds a GET endpoint for attendances

---

.env.sample
app/blueprints/child_blueprint.rb
app/models/child.rb
app/services/nebraska_full_days_calculator.rb
app/services/nebraska_hours_calculator.rb
client/package.json
client/yarn.lock
config/application.rb
lib/tasks/test698.rake
lib/tasks/test714.rake
package.json
spec/blueprints/child_blueprint_spec.rb
spec/models/child_spec.rb
spec/services/nebraska_full_days_calculator_spec.rb
spec/services/nebraska_hours_calculator_spec.rb
yarn.lock

closes #698 - this creates a Nebraska Full Days calculator based on the P4P Nebraska Model and the calculations being done in the prediction algorithm spreadsheet.  It assumes that any attendance greater than or equal to 5 hours and 45 minutes counts as a full day, unless it is greater than or equal to 14 hours and 45 minutes, at which point it becomes two full days
There's a convenient rake task you can run using `bundle exec rails test698:kids_and_schedules` which will populate one of the NE kids with a schedule of 7 hours, and one without a schedule at all, and give them each an Attendance with a nil `check_out` time.  The date used in the rake task is June 3rd, 2021; if QA happens in July, I'll change the date before we get there.  Both kids should have 1 full day in their June …

[PIE-698] Adds full_day calculations for Nebraska, based on feature flag

---

.github/workflows/ci.yml

No ticket - just needed to rectify a double-build on the E2E test step

Removes extra step from E2E process

---

app/models/attendance.rb
spec/models/attendance_spec.rb

Fixes #1385 by adding a validation to the attendance model to make sure check_out > check_in
Run the attendance_batches endpoint and try and add an attendance with a check_out time before the check_in time.  You should get an error.

[PIE-1385] Adds validation to attendance to make sure check_out is after check_in

---

app/blueprints/user_blueprint.rb
app/models/user.rb
spec/blueprints/user_blueprint_spec.rb
spec/models/user_spec.rb

Updates the as_of in the user blueprint to use the user's current timezone, and also simplifies the latest_attendance_in_month logic
Fixes #1429 
This is really only testable in the evening after UTC has rolled to tomorrow, so sometime in the evening CST someone should log into staging and make sure "as_of" says today :)

Updates the as_of in the user blueprint to use the user's current timzone

---

.env.sample
app/blueprints/child_blueprint.rb
app/models/child.rb
app/models/child_approval.rb
config/application.rb
spec/blueprints/child_blueprint_spec.rb
spec/factories/children.rb
spec/factories/nebraska_approval_amounts.rb
spec/models/child_approval_spec.rb
spec/models/child_spec.rb
spec/models/nebraska_approval_amount.rb

Updates the family fee to read dynamically from the db when the feature flag is flipped; moves all dashboard fields to a single ff again
Fixes #1038 
Change your env var to true for the feature flag (note we've reduced it down to one env var)
- flip the flag to "false" and restart the server
- create a temporary dashboard case for a nebraska child from the console
- visit the dashboard, you should see your family fee value
- create a nebraska_approval_amount with an effective date before today for the child's active child approval, with a *different* family fee amount
- flip the flag to "true" and restart the server
- you should see the family fee value from the approval amount instead of the dashboard case

[PIE-1038] Updates the family fee to read dynamically from the db

---

spec/models/attendance_spec.rb
spec/requests/api/v1/attendances_spec.rb

Fixes the attendance specs that keep failing because of the beginning of week not being set to Sunday
Fixes #1447 
Will be tested by CI

Fixes the attendance specs

---

.github/workflows/release-drafter.yml

No ticket for this, just a quick fix to try and get release drafter to work correctly.

Pointing at the wrong branch

---

app/controllers/application_controller.rb
config/environments/test.rb
db/seeds.rb
spec/blueprints/child_blueprint_spec.rb
spec/blueprints/user_blueprint_spec.rb
spec/factories/users.rb
spec/models/approval_spec.rb
spec/models/attendance_spec.rb
spec/models/child_spec.rb
spec/models/illinois_rate_spec.rb
spec/models/nebraska_rate_spec.rb
spec/models/schedule_spec.rb
spec/models/user_spec.rb
spec/requests/api/v1/attendances_spec.rb
spec/requests/api/v1/businesses_spec.rb
spec/requests/api/v1/children_spec.rb
spec/requests/api/v1/users_spec.rb
spec/support/helpers.rb

Ensures consistent use of Time.current, sets timezone in specs to UTC so we can catch timezone errors for CI locally

Ensures consistent use of Time.current, sets timezone in specs to UTC

---

client/src/Dashboard/Dashboard.js

This resolves #1697 confirm dashboard stats are removed and showing if 0

remove n/a stats and logic to not show other stats if 0

---

lib/tasks/attendances.rake

Closes #1539 
This adds Nebraska logic to the seed data for attendances.
You'll need rates in order to get the attendances to return earned revenue, so if you need that, run `bundle exec rails nebraska_rates20210813` first.
Run `bundle exec rails attendances`
You should now see attendances for Nebraska kids.

Adds NE attendance logic

---

client/src/App.js

Closes #1898 - changes the env var that's called to the runtime envs, so we can use the prod value for google analytics

Uses runtime env vars rather than build time env vars

---

app/blueprints/service_day_blueprint.rb
app/controllers/api/v1/service_days_controller.rb
app/models/service_day.rb
app/policies/service_day_policy.rb
client/src/AttendanceView/AttendanceView.js
client/src/AttendanceView/_tests_/AttendanceView.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
client/tailwind.config.js
config/routes.rb
spec/blueprints/service_day_blueprint_spec.rb
spec/policies/service_day_policy_spec.rb
spec/requests/api/v1/service_days_spec.rb
spec/support/api/schemas/service_day.json
spec/support/api/schemas/service_days.json

Closes #1866 
Closes #1862 
Closes #1724
Closes #1867
This adds a `service_days` endpoint to the API that returns an array of ServiceDays based on a filter_date, and the associated attendances, as well as the tags indicating the length of duration.
Log in as the Nebraska user and hit the /service_days endpoint, after populating attendances in your API

[PIE-1866] [PIE-1862] [PIE-1724] [PIE-1867] service_days endpoint, tags

---

client/src/App.js
client/src/Profile/Profile.js
client/src/Profile/index.js
client/src/_shared/Header.js
client/src/_shared/__tests__/Header.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

Closes #1798
Desktop: Verify the presence of avatar with user's initial. Click on it, then click on "My Profile/Mi Perfil" to navigate to the dummy profile page.
Mobile: Open the hamburger menu, click on "My Profile/Mi Perfil" to navigate to the dummy profile page.
- This PR does not include a selected state for "My Profile", as that's part of #1726
- A circular button was used instead of the AntD Avatar component mentioned in the issue for accessibility reasons.

[Pie-1798] I can access My Profile from the navigation

---

client/src/_shared/_hooks/useGoogleAnalytics.js

Closes #1953 
Click around, then go to GA Dashboard (I went to realtime, events, page_view, and then page_title).  You should see paths instead of only seeing "Pie for Providers"

[PIE-1953] Sets the page title based on the page path

---

app/controllers/api/v1/attendances_controller.rb
app/models/attendance.rb
config/routes.rb
spec/requests/api/v1/attendances_spec.rb

Closes #2035  It adds an update endpoint to the attendance api controller.  It does not include all the tests in the issue.  Would suggest splitting into separate issue for those tests to be written for coverage on the attendance model.

Pie 2035/api add update endpoint to attendance

---

client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js

Closes #2086 - this bug was introduced when we displayed auth period columns; they didn't account for inactive kids
- Go to dashboard and scroll to bottom to see inactive children (or mark one inactive)
- All fields should be populated with "-" including the total auth period columns

[PIE-2086] Fixes the authorization period columns for inactive kids

---

client/src/_shared/Header.js

Closes #2063 - the mobile menu wasn't explicitly setting the menu state to "closed" (which is what triggers the menu icon change) when clicking on a nav element, so this does it explicitly.
Click on the mobile menu in mobile view
Click on any item in the dropdown
The X should change back to a hamburger menu

[PIE-2063] Fixes the sticky X on mobile views

---

client/src/Attendance/Attendance.js
client/src/Attendance/AttendanceDataCell.js
client/src/Attendance/_tests_/AttendanceDataCell.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

Closes #1377 
- visit the add attendance page
- there should only be an `absent` checkbox, not one for covid
- change the date to a date before July 31 2021
- the `covid` absence checkbox should show up
- clear the date with the `x` icon in the date picker
- the `covid` absence checkbox should disappear
- choose another date before 7/31/2021
- the `covid` absence checkbox should show up again
- choose another date after 7/31/2021 _without using the `x` icon first_
- the `covid` absence checkbox should disappear again

[PIE-1377] Conditionally display COVID option

---

client/src/Dashboard/Dashboard.js

Closes #2087 - we were including inactive kids in the rollup numbers, this removes them.
- visit the dashboard
- check the totals in estimated and earned revenue columns
- they should match the rollups at the top (with rounding)

[PIE-2087] Only roll up numbers from active kids

---

app/controllers/api/v1/service_days_controller.rb
app/models/service_day.rb
app/policies/service_day_policy.rb
app/policies/user_policy.rb
client/src/AttendanceView/AttendanceView.js
spec/policies/service_day_policy_spec.rb
spec/policies/user_policy_spec.rb
spec/requests/api/v1/service_days_spec.rb
spec/requests/api/v1/users_spec.rb

Closes #2088 - we should be using the service day's dynamically calculated total time in care when we display duration on the view attendance page.  I also changed the controller policies so that Admins only see Nebraska information (for more info see my post in Slack in #general 
View an attendance record with no check out
The duration should still be showing (likely will be 8 hours if that's what the schedule is, or 8 hours by default if there's no schedule and it's not an absence)

[PIE-2088] view attendance duration

---

app/models/child.rb
app/services/wonderschool/necc/onboarding_case_importer.rb
spec/factories/children.rb
spec/services/wonderschool/necc/onboarding_case_importer_spec.rb
spec/spec_helper.rb

Fixes #2191 and unblocks #2190
The onboarding spreadsheet used to skip kids that already existed in the db; this adds logic to either add a new approval, update an existing approval, or add an updated approval and expire the old one if it overlaps.
Run an onboarding spreadsheet with kids that already exist and new approval info, it should update them as listed in the spec expectations
TODO: Still have to update if the approval dates are the same.

[PIE-2191] Onboarding accepts renewals

---

app/models/child.rb
spec/models/child_spec.rb

#2192 This fixes a bug that will refactor with_dashboard_case query for the dashboard to include children on the last day of their approval.

Pie 2192/bug fix dashboard query to include last day of approval

---

app/controllers/api/v1/service_days_controller.rb
app/models/attendance.rb
spec/models/attendance_spec.rb
spec/requests/api/v1/service_days_spec.rb

Supports #1170 - removes empty service days from API endpoint
Delete all attendances for a service day.  It should no longer show up in the endpoint returning service days.  It should be deleted.

Removes empty service days from response to API

---

app/models/approval.rb
app/models/child.rb
app/models/illinois_approval_amount.rb
app/models/nebraska/dashboard_case.rb
spec/models/child_spec.rb

We missed a scope last time and I also did a little logic cleanup on how we request dates in scopes

Changes scope on approval and child to include the last day of the approval for all views that use those scopes

---

app/jobs/seed_demo_attendances_job.rb
app/services/demo_attendance_seeder.rb
config/application.rb
config/environments/production.rb
lib/log/console_formatter.rb
lib/log/file_formatter.rb
lib/tasks/attendances.rake

This reworks the attendance seeder to avoid errors and overlapping attendances.  This also handles some of our nuisance tickets:
Fixes #1607 
Fixes #2142

Better attendance seeding

---

app/blueprints/business_blueprint.rb
app/blueprints/child_blueprint.rb
app/controllers/api/v1/children_controller.rb
client/src/Attendance/Attendance.js
client/src/Attendance/_tests_/Attendance.test.js
client/src/_shared/_hooks/useCaseAttendanceData.js
lib/tasks/prep.rake
spec/blueprints/business_blueprint_spec.rb

Changes the Edit Attendance Page to call to the Children endpoint, which does not limit the list to children with active approvals.
No ticket, this fixes a request from a customer directly.  However, this covers a prior ticket: #2128 
Ensure you have one student with no active approvals.  The student should show up on Edit Attendance, but not on the Dashboard
@cjhaddad the styling looked off to me when I ran it locally but my computer has been slow and buggy today, so it might have been a side effect.  Can you double-check?

Changes the Edit Attendance Page to call to the Children endpoint

---

app/controllers/api/v1/children_controller.rb
spec/requests/api/v1/children_spec.rb

Backend work for #2017 - does what it says on the tin
Authenticate as an admin user and hit the `GET /children` endpoint with no params, you should get back all the kids.  Hit the endpoint again with the body:
```
{
"child": {
"site": [
<business ID string>
}
}
```
You should see only the kids in that business.
If you send two strings, you should see the kids for both businesses; this array will accept any number of IDs
```
{
"child": {
"site": [
<business ID string>,
<business ID string>
}
}
```
If you log in as a non-admin user, send one of your business IDs, you should see the kids for that business.  Send another user's business IDs, and you shouldn't see those kids.

Adds filter to the children controller

---

app/blueprints/business_blueprint.rb
app/controllers/api/v1/users_controller.rb
app/policies/user_policy.rb
config/routes.rb
spec/blueprints/business_blueprint_spec.rb
spec/policies/user_policy_spec.rb
spec/requests/api/v1/users_spec.rb

closes #1794 
Test the `/profile` and `/users/:id` endpoints in Postman (under Authenticated Routes > Profile).
Both user and associated businesses should update. Only permitted fields will be allowed.

[PIE 1794] API buildout: Add PUT endpoint for user profile info

---

app/controllers/api/v1/children_controller.rb
spec/requests/api/v1/children_spec.rb

This fixes #2470 so business IDs can be sent to the children parameter to filter by business.  It also changes the param name to better represent the data model.  Now requests can be sent as follows:
```
/api/v1/children?business=2183e7ec-06e1-4f58-bbcc-bcfc6b4b6ff6,ff9edb05-afa1-4ded-ad95-0c39403d6560
```
Get a list of business IDs from your db.  Hit the endpoint:
```
/api/v1/children?business=2183e7ec-06e1-4f58-bbcc-bcfc6b4b6ff6,ff9edb05-afa1-4ded-ad95-0c39403d6560
```
should return all the kids belonging to two businesses
```
/api/v1/children?business=2183e7ec-06e1-4f58-bbcc-bcfc6b4b6ff6
```
should return only kids belonging to the first business
```
/api/v1/children
```
should return all kids in the user's scope

Changes the params to URL params

---

app/controllers/api/v1/service_days_controller.rb
app/policies/service_day_policy.rb
spec/requests/api/v1/service_days_spec.rb

Adds business param query to support #2378 
Hit the /service_days end point with a business=[] param, supports multiple ids

[PIE-2627] Adds business param query

---

spec/factories/approvals.rb

Extends expiry date in approval factory to normalize behavior of rate_associate. Will probably need a more permanent solution.

fixed expiry date to increase another year

---

app/blueprints/child_blueprint.rb
app/blueprints/illinois/dashboard_case_blueprint.rb
app/models/illinois/dashboard_case.rb
app/models/illinois_rate.rb
app/services/earned_revenue_calculator.rb
app/services/illinois/daily/days_duration_calculator.rb
app/services/illinois/daily/revenue_calculator.rb
app/services/illinois/earned_revenue_calculator.rb
app/services/illinois/service_day_calculator.rb
client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/_shared/_hooks/useCaseData.js
db/schema.rb
spec/models/illinois/dashboard_case_spec.rb
spec/spec_helper.rb

This allows to calculate earned revenues based on IL rules explained here: https://github.com/pieforproviders/pieforproviders/issues/2856
Make sure illinois_rates table has records on it. 
Add attendances to x child
Go to IL dashboard and make sure the avalues are reflected there.
There are several rates that can be applied to the same combination of business license, business region and child age. Each rate can have different values so it could be taking the undesired rate.

Calculating earned revenues for IL dashboard

---

app/models/user.rb
app/services/attendance_csv_importer.rb
spec/factories/users.rb
spec/models/user_spec.rb

Print message to user who is running the rake task directly on a console.
Upload an attendance file to the s3 bucket
run: rails attendance_csv_importer
Upload an attendance file
Upload an attendance file to the s3 bucket
run: heroku run bundle exec rails attendance_csv_importer -a pie-staging

Print messages to users when uploading attendances

---

client/src/Signup/Signup.js

https://github.com/pieforproviders/pieforproviders/issues/3196
Sign up with a new user account.
The masked input feature that automatically pre filled the phone input field with the format "123-456-7891" won't be applied anymore.

fix: [PIE-3196] [Fabian] Using regular input rather than masked input which has conflicts on latest versions

---

client/src/AttendanceView/AttendanceView.js
client/src/_shared/AttendanceDataCell.js
client/src/_shared/__tests__/AttendanceDataCell.test.js

#3190 This would add a remove check in button for the first  check in/out picker. This will only show up if there is a check in or check out time selected.  It will allow you to remove the check-in/out and delete an attendance on the attendance page like you can with a second attendance on the same day.

manually delete first attendance

---

app/mailers/devise_custom_mailer.rb

Users not able to submit new password after going through reset password flow.
This cannot be tested locally. It always worked there.
Try resetting a password for a any user in staging, demo or production.

fix: [PIE-3299] [Fabian] Changing URL for reset password link
