pieforproviders/pieforproviders

.github/workflows/ci.yml
.rubocop.yml

Adds cacheing to Github actions
Ticket: N/A
Speed up builds (maybe?)

Feature/cacheing in GitHub actions

---

.env.sample
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
client/src/Login/Login.js
config/environment.rb
spec/swagger_helper.rb

Adds documentation for OpenSource contribution, and a couple more tweaks to env vars
Ticket: https://app.asana.com/0/1148447927277945/1156685059400129/f
To clarify processes for new contributors!

Documentation update, config updates, etc.

---

app.json
client/src/App.js
client/src/index.js
static.json

Might need this static.json file to get the deployed env to route correctly.
Ticket: #22 URLs are 404s/not correctly routed

Static routing on Heroku

---

client/package.json
client/yarn.lock

Separate dev dependencies from dependencies in package.json

---

.gitignore
README.md
client/.env.development.sample
client/package.json
client/src/App.js
client/src/ErrorBoundary/ErrorBoundary.js
client/src/ErrorBoundary/index.js
client/src/index.js
client/yarn.lock

We need to set an environment variable `REACT_APP_SENTRY_DSN` before building the code for Production.
Sets up [Sentry](https://sentry.io) to track error events in Production. Fixes #47
When a user encounters an error, they get to share feedback that gets sent to Sentry along with the event information.

feat: Setup Sentry to track error events

---

README.md

Removes a stray line from the README. This PR is a docs update and I believe the following lists are unnecessary.

Remove stray step from README

---

client/src/Signup/Signup.js
client/src/_assets/styles/layouts/signup.css
client/src/_shared/forms/ValidationError.js
client/tailwind.config.js
client/tailwind/plugins/components/validationError.js

Changes field spacing, font-weight for labels, and icon size for error messages
QA bugs in #54 
Stop your yarn server and re-run `yarn start` or your `rails start` commands
Visit `localhost:3000/signup` and make sure the UI changes have been implemented

[54] QA Bugs

---

README.md

None, just notes from my onboarding last week.
nothing
Just new steps in onboarding md

made edits from onboarding experience

---

client/src/App.test.js
client/src/Login/Login.js

feature 98, log in error states
none
none 
none
none

style the errors

---

CONTRIBUTING.md
spec/requests/api/v1/businesses_spec.rb
spec/requests/api/v1/children_spec.rb

Refactor request specs to use factories instead of explicitly building non-tested records with params
N/A
CI tests should still pass
cc @weedySeaDragon take a look at these refactors, might impact your spec-writing on #171

Refactor request specs to use factories

---

db/seeds.rb

https://github.com/pieforproviders/pieforproviders/issues/237
And confirms the user account created from the seeds.
`rails db:drop && rails db:setup`

Turn off email deliveries when seeding the database

---

.github/PULL_REQUEST_TEMPLATE.md

Does what it says on the tin 🙂

Add running rspec tests to the PR checklist

---

client/src/Signup/Confirmation.js

https://github.com/pieforproviders/pieforproviders/issues/247
Fixes the list items alignment issue on the signup confirmation page.
**Screenshots**
1. Sign up for an account.
2. Inspect the list items alignment on the confirmation page on both mobile and desktop screens.

Fix list items alignment issue

---

.github/workflows/ci.yml

changing primary branch for prod deployment in CI to main for future prod branch.

Rename primary branch for CI

---

client/tailwind.config.js

https://github.com/pieforproviders/pieforproviders/issues/258
Opts into [Tailwind's breaking changes](https://tailwindcss.com/docs/upcoming-changes).
Visit all the pages and make sure none are broken

Update Tailwind config to opt-in to breaking changes

---

README.md

Fixes build link

---

client/src/i18n/locales/es/index.json

Translations from #254 comments

Translations from #254

---

client/src/GettingStarted/GettingStarted.js

https://github.com/pieforproviders/pieforproviders/issues/280
Updates the font size of the icons to **large**.
**Before**
**After**
Log in and go to `/getting-started`.

Update icons size on the Getting Started page

---

app/controllers/api/v1/child_case_cycles_controller.rb
config/routes.rb
spec/requests/api/v1/child_case_cycles_spec.rb
spec/support/api/schemas/child_case_cycle.json
spec/support/api/schemas/child_case_cycles.json
spec/swagger_helper.rb
swagger/v1/swagger.json

ChildCaseCycle: add controller, request spec, api jsons, update swagger

---

lib/tasks/address_lookup_items.rake

#335 
I modified the rake tasks that import information in the db.
1. You can re-seed the db by running `bundle exec rails db:seed:replant` , OR
2. you can import manually:
- after truncating the lookup tables, you can run `bundle exec rails pie4providers:address_lookups:import`

Importing: change ALL CAPS to First Letter Capitalized: state, county, city name

---

app/controllers/api/v1/children_controller.rb
app/controllers/api/v1/sites_controller.rb
app/models/site.rb
app/policies/child_policy.rb
app/policies/site_policy.rb
spec/policies/child_policy_spec.rb
spec/policies/site_policy_spec.rb
spec/requests/api/v1/children_spec.rb
spec/requests/api/v1/sites_spec.rb
swagger/v1/swagger.json

#178
Adds policies for sites and children. Depends on #331.

Add policies for sites and children

---

.github/workflows/ci.yml

Triggering some CI Actions for identification

Adds some steps for identification to github CI workflow

---

.github/workflows/ci.yml

Only run e2e tests on merge to develop

---

config/routes.rb

Only exposes `GET /users` and `GET /users/:id` routes.

Update user routes

---

package.json
spec/cypress/integration/resetPassword.spec.js
yarn.lock

Replace moment with dayjs

---

spec/requests/api/v1/users_spec.rb
spec/requests/confirmations_spec.rb
spec/requests/registrations_spec.rb
spec/support/shared_examples_api_request.rb
swagger/v1/swagger.json

The API doesn't need to support XML data.

Remove application/xml from swagger doc

---

app/controllers/api/v1/sites_controller.rb
app/controllers/registrations_controller.rb

Fixes typo and removes unnecessary comment

---

package.json
yarn.lock

This was already removed in https://github.com/pieforproviders/pieforproviders/commit/0888446a81e71833653185803563257331149eb0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L54 but it got added back in https://github.com/pieforproviders/pieforproviders/commit/cc64ca1c4eecf3b363d1fadc2f47dd54c5295ec4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R55 😕

chore: Remove moment

---

client/src/App.js
client/src/_utils/_routes/AuthenticatedRoute.js

Chore related to #180 - renaming route to be more semantic
Visit an authenticated route while logged in, it should work
Visit an authenticated route while logged out, it should stop working

Rename AuthorizedRoute to AuthenticatedRoute

---

db/seeds.rb

#332 - seed fixes that got missed
```
bundle exec rails db:reset
bundle exec rails db:seed # if necessary
```

Fixes seeds

---

lib/tasks/remove_migrations.rake

Remove duplicate frozen string literal comment

---

package.json

No ticket; timeouts on Github actions

Changes timeout on cypress to stop failing tests on Github actions

---

client/src/_shared/LoggedInLayout.js

* [ x] Did you run `yarn lint` in `/client`?

expend background to 100% height

---

client/src/_shared/LoggedInLayout.js

h-full only for large screens

---

client/src/Dashboard/Dashboard.js
client/src/_assets/styles/tag-overrides.css

adjust fontsize to tags to 14px

---

package.json
spec/cypress.json
spec/cypress/integration/casesImport.spec.js
spec/cypress/integration/confirmation.spec.js
spec/cypress/integration/login.spec.js
spec/cypress/integration/resetPassword.spec.js
spec/cypress/integration/resetPasswordRequest.spec.js
spec/cypress/integration/signup.spec.js
yarn.lock

Upgrades Cypress following the [migration guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-6-0).
- Removes `experimentalFetchPolyfill` config
- Removes `cy.server` call and replaces `cy.route` with `cy.intercept`

Bump cypress to 6.0.1

---

app/models/illinois_subsidy_rule.rb
spec/factories/illinois_subsidy_rules.rb
spec/models/illinois_subsidy_rule_spec.rb

Annotate models

---

db/data/20201216142801_add_nebraska_cases.rb
db/data_schema.rb

Fix for nebraska cases on staging

---

spec/factories/approvals.rb

https://github.com/pieforproviders/pieforproviders/issues/694
The current approval factory randomly chooses an `effective_on` date [between a year ago and the current date](https://github.com/pieforproviders/pieforproviders/blob/76155a9b82ebd6735846656f4d54e608a35bdf92/spec/factories/approvals.rb#L8). If the chosen date is exactly a year ago, [the approval becomes `expired`](https://github.com/pieforproviders/pieforproviders/blob/76155a9b82ebd6735846656f4d54e608a35bdf92/spec/factories/approvals.rb#L9) making the child in the test have no current approvals. The PR makes sure the generated `expired_on` date is always in the future — i.e. the approval is active. The [`expired_approval` factory](https://github.com/pieforproviders/pieforproviders/blob/76155a9b82ebd6735846656f4d54e608a35bdf92/sp …

Fix flaky children request spec

---

Procfile
config/environments/production.rb

This fixes the issue we ran in to when migrating the database on Staging. Thanks @bensheldon!

Pass GoodJob settings via environment variables

---

app/services/approval_amount_generator.rb
spec/factories/children.rb
spec/requests/api/v1/children_spec.rb

https://github.com/pieforproviders/pieforproviders/issues/755
The date string should be passed as the first argument to `Date.parse`. The current code just passes the month `March` as the date string  — the year defaults to the current year. This should explain why the test was passing in 2020 🙂

Fix failing case list for dashboard spec

---

client/src/Dashboard/DashboardTable.js

add spacing

---

app/blueprints/user_blueprint.rb
app/models/illinois_approval_amount.rb
app/services/illinois_attendance_risk_calculator.rb
spec/factories/approvals.rb
spec/factories/children.rb
spec/requests/api/v1/users_spec.rb

Adds helper scope to illinois_approval_amounts, tweaks time logic on specs/approval factory, refactors child spec, massive refactor of examples and expectations on users spec for new endpoint
No issue, fixes failed builds

Bugfix on algorithms and specs for the new endpoint

---

client/src/Dashboard/Dashboard.js

update how mx rev and total approved are being created

---

client/src/Signup/Signup.js

* [ x] Did you run `yarn lint` in `/client`?
confirm that the email is taken error goes away once you begin typing again

reset validation errors after email taken error to remove it from UI

---

client/src/Dashboard/DashboardStats.js

styling tweaks to dashboard summary stats

---

.env.sample
client/.env.sample
client/package.json
client/src/index.js
client/yarn.lock
config/initializers/sentry.rb

Sets up Sentry to send environment information with error messages

Sentry configuration

---

client/src/Confirmation/Confirmation.js
client/src/Login/Login.js
client/src/PasswordReset/NewPassword.js
spec/cypress/integration/confirmation.spec.js
spec/cypress/integration/login.spec.js
spec/cypress/integration/resetPassword.spec.js
spec/cypress/support/index.js

#628 redirecting to dashboard
* [ X] Did you run `yarn lint` in `/client`?
* [X ] Did you run `yarn test` in `/client`?
upon login you are redirected to the /dashboard route
upon signup and confirmation you are redirected to the /dashboard route

change all redirects of getting-started to dashboard

---

app/controllers/api/v1/users_controller.rb
spec/requests/api/v1/users_spec.rb

#916 
Adds an admin check to the blueprint that will direct admins to the nebraska dashboard
- log in as an admin, you should be directed to the nebraska dashboard view instead of the illinois one.

Defaults admins to nebraska, fixes specs

---

client/src/Dashboard/DashboardDefinitions.js
client/src/i18n/locales/es/index.json

fix punctuation and tag color

---

client/src/Dashboard/Dashboard.js

Sentry typerror bug!
regression test, make sure both IL and NE users' dashboards work and sentry error no longer is showing.

add null check for summary totals

---

client/src/Dashboard/Dashboard.js

Reverts pieforproviders/pieforproviders#934 - need to revert this because it caused some additional issues

Revert "add null check for summary totals"

---

docs/narrative_data_model.md

Add child's address to ensure he/she is a resident of Illinois. Providers cannot receive the subsidy for non-residents

TBD Note - add child's address

---

client/src/Dashboard/Dashboard.js

fix lint errors
* [ x] Did you run `yarn lint` in `/client`?

add null operator to check for matches

---

Gemfile.lock
app/blueprints/child_blueprint.rb

Fixes type of return value as well as reverting broken dependabot update 🙄
#947 
`bundle install` and start the server and the front end - might want to reset your db in case you don't have any TemporaryNebraskaDashboardCase records
- visit the nebraska dashboard
- no frontend errors and earned and estimated revenue for each kid should display correctly, as floats

[947] Fixes type of return value for NE Dashboard bug

---

client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/_utils/constants.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

[951] add ahead of schedule tag to dashboard table tags

---

client/src/Dashboard/Dashboard.js

set 'n/a' for max rev, total approved, and transportation

---

client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

add spanish translations for various words on the dashboard table

---

app/services/subsidy_rule_associator.rb
app/services/wonderschool/necc/attendance_downloader.rb
app/services/wonderschool/necc/dashboard_downloader.rb
app/services/wonderschool/necc/onboarding_downloader.rb
db/seeds.rb
spec/factories/approvals.rb
spec/factories/subsidy_rules.rb
spec/models/child_spec.rb
spec/services/illinois_attendance_rate_calculator_spec.rb
spec/services/wonderschool/necc/attendance_downloader_spec.rb
spec/services/wonderschool/necc/dashboard_downloader_spec.rb
spec/services/wonderschool/necc/onboarding_downloader_spec.rb

DateTime changes and ActiveJob test helpers to try and fix this flaky spec - subsidy rule associator is not working how I want
#978

[978] Flaky/not-flaky spec preventing builds

---

Procfile

#1053 
When this is deployed we'll check the run on heroku staging and make sure it ran without the `with_data` command

Updates procfile to remove with_data

---

client/src/Dashboard/DashboardTable.js

update currency formatter

---

client/src/Dashboard/DashboardDefinitions.js
client/src/Dashboard/__tests__/DashboardDefinitions.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

add ahead of schedule tag to the definitions panel

---

client/src/i18n/locales/es/index.json

remove excess def from the estimated rev def

---

client/src/i18n/locales/es/index.json

update ahead of schedule translation

---

client/src/Dashboard/DashboardTable.js

fix family fee sorting function

---

client/src/Dashboard/DashboardTable.js

add match and replace for spanish translation for month abbreviations

---

client/public/index.html

remove extra R

---

client/package.json
client/src/App.js
client/src/_utils/appSignal.js
client/yarn.lock

[When the Staging app is promoted to Production, the app isn't rebuilt](https://devcenter.heroku.com/articles/pipelines#deployment-with-pipelines) and so the frontend JS bundle with the environment variables from Staging gets deployed to Production.  This PR fixes the issue by replacing compile-time variables with runtime ones. This also has the added benefit of updating the app immediately when the environment variables get changed. To get this to work, we should do the following steps:
1. Add `create-react-app-inner-buildpack` to the Production app buildpacks. This buildpack enables runtime environment variables.
```bash
heroku buildpacks:add -i 1 https://github.com/mars/create-react-app-inner-buildpack
```
2. Add the `JS_RUNTIME_TARGET_BUNDLE` environment variable to point to the JS …

fix: Replace compile-time env vars with runtime env vars

---

client/src/constants.js
config/initializers/devise.rb

Change confirmation email

---

db/seeds.rb

N/A Does what it says on the tin; makes it so I can reseed demo

Updates seeds to match expected dashboard inputs

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/engineering_task.md
.github/ISSUE_TEMPLATE/feature_request.md

Updates the typo in codeowners and updates the issue templates to include a states checklist

Updates the typo in codeowners and updates the issue templates

---

app/models/illinois_rate.rb
spec/factories/approvals.rb
spec/factories/illinois_rates.rb
spec/models/illinois_rate_spec.rb
spec/services/illinois_attendance_rate_calculator_spec.rb
spec/services/wonderschool/necc/attendance_downloader_spec.rb
spec/services/wonderschool/necc/attendance_processor_spec.rb
spec/services/wonderschool/necc/dashboard_downloader_spec.rb
spec/services/wonderschool/necc/dashboard_processor_spec.rb
spec/services/wonderschool/necc/onboarding_downloader_spec.rb
spec/services/wonderschool/necc/onboarding_processor_spec.rb

No ticket - just documenting todos

Todos and comments from working on 714

---

app/services/illinois_attendance_risk_calculator.rb

N/A we had a nil comparison bug for attendance risk, this does a safer fallthrough

[Bugfix] children without active child approvals

---

client/src/Dashboard/DashboardTable.js

add space between childname and inactive

---

client/src/Dashboard/DashboardTable.js

extra space

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config.ru
config/appsignal.yml
config/initializers/backtrace_silencers.rb
config/initializers/good_job.rb
config/initializers/sentry.rb

Remove old Raven configs, add AppSignal to Backend

---

.env.sample
app/models/child.rb
config/application.rb
config/initializers/backtrace_silencers.rb
lib/tasks/test714.rake
spec/blueprints/child_blueprint_spec.rb
spec/models/child_spec.rb

Fixes rake task for July, updates the feature flag env var name, so we can have a separate one for each calculation, and fixes the backtrace cleaner to prevent nils
Closes #714

Fixes rake task for July

---

app/services/nebraska_hours_calculator.rb
spec/services/nebraska_hours_calculator_spec.rb

Closes #714 with corrected math
N/A

Fixes the math based on Jon's findings

---

app/models/business.rb
app/services/s3_csv_importer.rb
app/services/wonderschool/necc/attendance_csv_importer.rb
app/services/wonderschool/necc/dashboard_csv_importer.rb
app/services/wonderschool/necc/onboarding_csv_importer.rb

Bugfixes for the CSVs

---

client/src/Attendance/Attendance.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

this addresses #1376 and renders an error when a date for the column in not selected and needs to be.
WIP bc disabling of Save logic needs to be tweaked, but putting this PR up now for preliminary review

Pie 1376/attendance input errors

---

app/lib/aws_client.rb

The changes to the AWS client were throwing errors when trying to upload a CSV, hoping these fixes will get us back on track

Updates the client for AWS

---

app/lib/appsignal_reporting.rb
app/lib/aws_client.rb
app/services/csv_parser.rb
app/services/wonderschool/necc/attendance_csv_importer.rb
app/services/wonderschool/necc/dashboard_case_importer.rb
app/services/wonderschool/necc/onboarding_case_importer.rb
spec/lib/appsignal_reporting_spec.rb

Appsignal send_error requires the whole exception to be sent, not just the message.

Appsignal reporting

---

lib/tasks/wonderschool_tasks.rake

Rake tasks have to call appsignal.stop to send I guess.  Not sure why this is working in local though

Appsignal stop requirement

---

config/appsignal.yml
lib/tasks/wonderschool_tasks.rake

Running in container to true, sleep 5 after stopping appsignal so it has time to send to the API

More config for Appsignal

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/engineering_task.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Updates the docs, removes old references and instructions that aren't relevant anymore.

Docs Update

---

app/blueprints/attendance_blueprint.rb
app/blueprints/child_blueprint.rb
app/models/attendance.rb
spec/blueprints/attendance_blueprint_spec.rb
spec/blueprints/child_blueprint_spec.rb
spec/support/api/schemas/attendance.json
spec/support/api_schema_matcher.rb

Closes #1556 
- hit the attendances endpoint
- attendances should now include the child in the following format:
```
{
"id": "4f291296-e867-485e-80da-dc7c89fb784c",
"absence": null,
"check_in": "2021-08-24 07:22:49 UTC",
"check_out": "2021-08-24 18:39:49 UTC",
"child": {
"id": "a033d8f4-618f-4c5f-8ee4-c0dd613f99fe",
"active": true,
"full_name": "Maria Baca",
"inactive_reason": null,
"last_active_date": null
},
"child_approval_id": "83e173cf-53db-44ed-b6ee-9dbefd501de1",
"total_time_in_care": "40620"
},
```

[PIE-1556] Adds child to the attendance blueprint

---

README.md
app/models/approval.rb
app/models/child.rb
spec/blueprints/child_blueprint_spec.rb
spec/factories/nebraska_rates.rb
spec/models/approval_spec.rb
spec/models/attendance_spec.rb
spec/models/child_spec.rb

No ticket associated with this

Family Fee calculations, missing test

---

app/blueprints/child_blueprint.rb
app/models/child.rb
app/services/nebraska_weekly_hours_attended_calculator.rb
lib/tasks/nebraska_dashboard_deploy.rake
spec/blueprints/child_blueprint_spec.rb
spec/services/nebraska_weekly_hours_attended_calculator_spec.rb

Continued work on #712 and all the others!
See steps in #712

Dashboard bugfixes

---

app/blueprints/user_blueprint.rb
app/controllers/application_controller.rb
app/models/attendance.rb
app/models/child.rb
app/models/user.rb
app/services/illinois_attendance_risk_calculator.rb
app/services/time_zone_service.rb
spec/blueprints/child_blueprint_spec.rb
spec/models/user_spec.rb

This removes all individual calls to `in_time_zone` in favor of setting the user's timezone for each API request before the request occurs, which makes behavior consistent across the application.
Specs still use `in_time_zone` in order to make sure what the user sees is consistent with what they expect; some of this could be fleshed out later and should be.
Test the dashboard again!

Clarify time math

---

client/package.json
client/src/App.js
client/src/Confirmation/Confirmation.js
client/src/Dashboard/Dashboard.js
client/src/GettingStarted/GettingStarted.js
client/src/Login/Login.js
client/yarn.lock

remove react-hotjar and add react-use-hotjar

---

app/models/child.rb
app/services/nebraska_absence_generator.rb
spec/blueprints/child_blueprint_spec.rb
spec/services/nebraska_absence_generator_spec.rb

Dashboard discrepancies

---

app/models/child.rb

Fix the date

---

Gemfile
Gemfile.lock
spec/requests/api/v1/attendances_spec.rb

https://github.com/pieforproviders/pieforproviders/issues/1447
Update `attendance_spec` to fix flakiness it tests runs on CI

Update Attendance Spec

---

spec/requests/api/v1/attendances_spec.rb

https://github.com/pieforproviders/pieforproviders/issues/1447

Flaky attendances spec - Attempt 2

---

spec/services/nebraska_absence_generator_spec.rb

Yet another flaky spec due to time math 😢

Fixes the flaky spec

---

spec/factories/approvals.rb
spec/models/child_spec.rb
spec/requests/api/v1/attendance_batches_spec.rb

No ticket, just some failed branches

Fixes the setup of the attendance batches spec to avoid unclear dates

---

client/src/Attendance/Attendance.js

add tag for testing

---

client/package.json
client/yarn.lock

remove unused csv module

---

client/package.json
client/src/App.js
client/src/App.test.js
client/src/Attendance/Attendance.js
client/src/Attendance/_tests_/Attendance.test.js
client/src/AttendanceView/AttendanceView.js
client/src/AttendanceView/_tests_/AttendanceView.test.js
client/src/AuthStatusAlert/AuthStatusAlert.js
client/src/Confirmation/Confirmation.js
client/src/Dashboard/DashboardTitle.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/Dashboard/__tests__/DashboardTitle.test.js
client/src/ErrorBoundary/__tests__/ErrorBoundary.test.js
client/src/Login/Login.js
client/src/PasswordReset/NewPassword.js
client/src/Signup/ConfirmationSent.js
client/src/_shared/ErrorDisplay.js
client/src/_shared/Header.js
client/src/_shared/__tests__/ErrorDisplay.test.js
client/src/_shared/__tests__/Header.test.js
client/src/_shared/__tests__/LoggedInLayout.test.js
client/src/_shared/_hooks/useUnauthorizedHandler.js
client/src/_utils/_routes/AuthenticatedRoute.js
client/yarn.lock

Reverts pieforproviders/pieforproviders#1936

Revert "Query string enhance/1744 standartize active vs inactive behavior"

---

client/src/AttendanceView/AttendanceView.js
client/src/AttendanceView/_tests_/AttendanceView.test.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
client/tailwind.config.js

This PR addresses: 
#1724 
#1867 
go to attendance view and confirm that attendance tags are coming through:
'full days' and 'hours' in green
'absent' in orange and without any checkin data
also regression test to ensure attendance data cells still are working

[WIP] Pie 1724/attendance tags and parse new data

---

app/blueprints/business_blueprint.rb
app/models/child.rb

No ticket; there were dupes in the staging dashboard

Fixes dupes in the dashboard

---

client/src/AttendanceView/AttendanceView.js

check 'absence' instead of 'absent'

---

client/src/Dashboard/Dashboard.js
client/src/Dashboard/DashboardTitle.js
client/src/Dashboard/__tests__/DashboardTitle.test.js
client/src/_shared/_hooks/useCaseData.js

Closes #1090 
- visit the dashboard as nebraska@test.com and admin@test.com
- you should see the date filtering dropdown
- it should change to prior values as expected

[PIE-1090] Updates the Dashboard to turn on date filtering for both states

---

app/models/attendance.rb
app/models/nebraska/dashboard_case.rb
app/models/service_day.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/models/attendance_spec.rb
spec/models/service_day_spec.rb

Closes #1924 
Adjusts total_time_in_care calculations to match AC, covers the new behavior with tests
This will need a spreadsheet confirmation, along with the other changes, just to be sure we've got the logic right for our existing kids.

[PIE-1924] refactor and testing for service day total time in care method

---

client/src/Attendance/Attendance.js
client/src/Dashboard/Dashboard.js
client/src/Dashboard/DashboardTable.js
client/src/Dashboard/DashboardTitle.js

#1090 surfaced this issue
- Log into the dashboard using nebraska@test.com and admin@test.com
- Choose a different month in the dropdown
- You should see new data in the attendances and revenue columns and the Hours Attended column should disappear
@cjhaddad please double check my work, I'm rusty at this useState and passing of methods stuff.

No ticket/bug from dropdown

---

client/src/_shared/Header.js

Closes #1803 by adding some enhancements to the mobile UI

Adds mobile enhancements to the header

---

client/src/ErrorBoundary/__tests__/ErrorBoundary.test.js
client/src/_assets/styles/button-header.css
client/src/_shared/Header.js
client/src/_shared/__tests__/ErrorDisplay.test.js
client/src/_shared/__tests__/Header.test.js
client/src/_shared/__tests__/LoggedInLayout.test.js

Closes #1726 - adds a "selected" underline to the navigation bar and mobile dropdown navigation menu to indicate what page the user is on
Visit the dashboard.  "Dashboard" in the nav bar should be underlined.
Visit the attendances page.  "Attendance" in the nav bar should be underlined.
Visit the attendances edit page.  "Attendance" in the nav bar should be underlined.

Selected underline

---

client/src/Dashboard/DashboardTitle.js

only send year and month to date filtering event

---

client/src/_shared/Header.js
client/src/_shared/__tests__/Header.test.js

closes #1798 - Added underline to "My profile" link when user is on that page (selected state).

[PIE-1798] Added selected state to My Profile link

---

app/blueprints/business_blueprint.rb
app/blueprints/user_blueprint.rb
app/controllers/api/v1/users_controller.rb
client/src/_shared/Header.js
client/src/_shared/__tests__/Header.test.js
spec/blueprints/business_blueprint_spec.rb
spec/blueprints/user_blueprint_spec.rb

Closes #1793 - rebased against uchicago-techteam after a lot of changes to develop

[REBASED] [PIE-1793] get user profile information

---

client/src/AttendanceView/AttendanceView.js

Fixes the math

---

client/src/AttendanceView/AttendanceView.js

Updates the logic for parsing the new endpoint

---

app/models/child.rb
app/models/service_day.rb
app/models/user.rb

Improving performance on the Dashboard Case feature by reducing the number of queries used to generate.

Reducing query load

---

README.md

I ran into this problem when standing up a new instance and thought
other people might too; m1s are still kind of yak-shavey. No problems
with the rest of the instructions 👍
This is a documentation-only PR, so the below checkboxes don't apply.
n/a

Add troubleshooting for postgres on m1

---

app/blueprints/child_blueprint.rb
app/models/nebraska/dashboard_case.rb
app/models/service_day.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/blueprints/user_blueprint_spec.rb
spec/models/nebraska/dashboard_case_spec.rb

N/A - bugs found on deploy to staging

Fix dashboard bugs

---

.env.sample
Gemfile
Gemfile.lock
app.json
app/blueprints/child_blueprint.rb
app/controllers/application_controller.rb
app/models/nebraska/dashboard_case.rb
app/models/service_day.rb
app/services/nebraska/weekly/attended_hours_calculator.rb
client/src/App.js
client/src/Confirmation/Confirmation.js
client/src/_shared/AuthLayout.js
client/src/_shared/LoggedInLayout.js
config/initializers/rack_profiler.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/models/nebraska/dashboard_case_spec.rb
spec/services/nebraska/weekly/attended_hours_calculator_spec.rb

Performance Improvements

---

app/models/nebraska/dashboard_case.rb
app/services/nebraska/monthly/attendance_risk_calculator.rb
config/initializers/rack_profiler.rb
spec/blueprints/child_blueprint_spec.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/services/nebraska/monthly/attendance_risk_calculator_spec.rb

I was missing some logic in my calculating attendance risk; the spreadsheet doesn't incorporate family fee in that calculation but I was passing the revenue that was being calculated after removing family fee.  This fixes that.

Performance mistakes

---

client/src/Dashboard/DashboardTitle.js
client/src/Payment/paymentDataCell.js
client/src/Payment/paymentModal.js
client/src/_assets/styles/payment-table-overrides.css

added payment modal resize

---

app/services/wonderschool/necc/onboarding_case_importer.rb
spec/services/wonderschool/necc/onboarding_case_importer_spec.rb

Adds logic to handle overlapping Nebraska Approval Amounts

---

app/blueprints/attendance_blueprint.rb
app/controllers/api/v1/attendances_controller.rb
app/controllers/api/v1/service_days_controller.rb
config/routes.rb
spec/blueprints/attendance_blueprint_spec.rb
spec/requests/api/v1/attendances_spec.rb
spec/support/api/schemas/attendance.json

Adds a delete endpoint for attendances and adds wonderschool_id to the return blueprint in support of #1170

Pie 1170/edit attendance tweaks

---

app/controllers/api/v1/payments_controller.rb
app/models/payment.rb
app/policies/payment_policy.rb
config/routes.rb
spec/requests/api/v1/payments_spec.rb
spec/support/api/schemas/payment.json
spec/support/api/schemas/payments.json

closes #1643 
* [] Did you run Google Lighthouse and/or WebAIM (Wave) on UI components in your PR?
* [] Does your PR contain any required translations?
* [] Are your primary keys UUIDs on any new tables?
* [] Migrations
* [] Dependencies
Not sure if the scope is exactly what is wanted, but can change if we need. Also currently if no filter_date is specified it returns all payments, not sure if we want to limit it to only the current month or something...

payments index

---

client/src/Dashboard/DashboardTitle.js
client/src/Payment/paymentDataCell.js
client/src/Payment/paymentModal.js

fixed roudning bug and set max for payment input

---

app/blueprints/user_blueprint.rb
spec/blueprints/user_blueprint_spec.rb

Closes #2242.
- `bundle exec rspec`
- Log in with Nebraska test user, then refresh dashboard page. This PR fixed an error that used to appear at this point.

Added user's state to profile view

---

app/models/attendance.rb
client/src/_shared/_hooks/useApiResponse.js
spec/models/attendance_spec.rb

Adds back in the logic to remove old service days from attendances that have been moved, when it's the last attendance on that day

Adds back in the logic to remove old service days from attendances

---

client/src/Dashboard/Dashboard.js

fixed minor bugs---toFixed() formatting problem when rendering the dashboard page---for issue#1175
https://github.com/pieforproviders/pieforproviders/issues/1175
Deployment not affected
No Change from the origin env
In dev mode, rendering the dashboard page will not cause errors
N/A

fixed toFixed() formatting problem

---

spec/cypress/app_commands/perform_enqueued_jobs.rb
spec/cypress/integration/attendanceView.spec.js

Cypress fixes

---

spec/models/attendance_spec.rb

Fixes broken test setup for attendance validation

---

.github/workflows/backend-ci.yml
spec/models/service_day_spec.rb

Turns brakeman back on and updates a flaky spec

---

spec/models/attendance_spec.rb

Fixes flaky attendance spec

---

app/jobs/seed_demo_attendances_job.rb

Typo in method definition, fixed.

Fix demo attendance seeding

---

client/src/Dashboard/Dashboard.js
client/src/Dashboard/__tests__/Dashboard.test.js
client/src/_shared/LoggedInLayout.js

Closes #2244 
1. Navigate to any page other than the dashboard
2. Reload
3. Inspect network requests and/or `setUser` in Redux dev tools to confirm that the user is fetched

Moved call to /profile endpoint to LoggedInLayout.js

---

app/models/user.rb
spec/models/user_spec.rb
spec/requests/registrations_spec.rb

Remove greeting_name and organization as required attributes for user

---

client/src/Signup/Signup.js
client/src/_assets/styles/form-overrides.css
client/src/_shared/AuthLayout.js
client/src/_shared/Header.js
client/src/i18n/locales/es/index.json
client/tailwind.config.js

Pie 2212/signup changes

---

app/services/attendance_csv_importer.rb
config/application.rb
spec/fixtures/files/Test Child Care-Grid view.csv
spec/services/attendance_csv_importer_spec.rb
spec/services/wonderschool/necc/attendance_csv_importer_spec.rb

Closes #2051 - we'll need to adapt as we get in more info but this should serve the general purpose.

Attendance Importer - some duped code but no need to over-optimize yet

---

spec/models/user_spec.rb
spec/services/attendance_csv_importer_spec.rb

Fixes time comparison specs and rubocop on another branch

---

.github/workflows/backend-ci.yml
.github/workflows/e2e-ci.yml
.github/workflows/frontend-ci.yml

Removes modification on github checkout action

---

client/src/Dashboard/DashboardTitle.js
client/src/_assets/styles/payment-table-overrides.css

fixed jumping actions button

---

app/controllers/api/v1/children_controller.rb
app/controllers/api/v1/service_days_controller.rb
app/models/child.rb
spec/requests/api/v1/children_spec.rb
spec/requests/api/v1/service_days_spec.rb

#2374  This would update the dashboard db calls to order the children by last_name

change backend to return children sorted by last name

---

app/services/attendance_csv_importer.rb
db/seeds.rb
lib/tasks/attendance_csv_importer.rake
spec/services/attendance_csv_importer_spec.rb

Edits seeds to include DHS ID, updates the archive method to take on current timestamp to avoid overwrites, adds rake task to call importer easily

QA Findings from Attendance Import

---

app/controllers/api/v1/children_controller.rb
app/models/child.rb
client/src/Dashboard/Dashboard.js
client/src/Dashboard/DashboardTable.js

Fixes the bug found during QA.

Fixes default sort

---

app/blueprints/attendance_blueprint.rb

Pulls out an unnecessary to_s conversion

Attendance performance improvements

---

client/src/_shared/Header.js
client/src/_shared/__tests__/Header.test.js

Closes #2420 
1. Log in as Nebraska Provider
2. Verify that the avatar in the header displays N (for Nebraska) instead of C (for Candice)

Replace greeting_name with full_name in Header avatar

---

client/src/Login/Login.js
client/src/Signup/Signup.js
client/src/_assets/styles/form-overrides.css
client/src/_assets/styles/next-button-overrides.css
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
client/tailwind.config.js

Resolves #2250 and makes updates to signup and login pages.

Pie 2250/signup login changes

---

client/src/Dashboard/DashboardTitle.js

fixed dropdown icon

---

.rubocop_todo.yml
app/models/service_day.rb
client/src/AttendanceView/AttendanceView.js
spec/models/service_day_spec.rb

#2431 This would update the tags on the view attendance page to show the calculated amount for both daily and hourly.

view attendance tags show billable numbers

---

client/src/Login/Login.js
client/src/Signup/Signup.js
client/src/_assets/styles/form-overrides.css
client/src/i18n/locales/es/index.json

Closes #2250 with requested changes from @rebeccakarasiktw

styling changes

---

app/policies/user_policy.rb
spec/policies/user_policy_spec.rb
spec/requests/api/v1/users_spec.rb

I don't want to limit the user endpoint to NE for admins; I'll need to limit the user blueprint instead.

No ticket/fix scope for user policy

---

app/controllers/api/v1/users_controller.rb
app/models/user.rb

Adds NE scope to user for use in the dashboard endpoint

---

app/blueprints/business_blueprint.rb
client/src/Attendance/Attendance.js
client/src/Attendance/_tests_/Attendance.test.js
client/src/ComingSoon/ComingSoon.js
client/src/Confirmation/Confirmation.js
client/src/Dashboard/Dashboard.js
client/src/Dashboard/__tests__/Dashboard.test.js
client/src/_assets/styles/select-overrides.css
client/src/_reducers/businessesReducer.js
client/src/_reducers/rootReducer.js
client/src/_reducers/uiReducer.js
spec/blueprints/business_blueprint_spec.rb

- Move getCaseData out of useEffect so we can call it when we change the filter

[PIE-2017] frontend filter components

---

client/src/Payment/paymentDataCell.js

fixed editable input

---

client/src/Attendance/Attendance.js

Bugs from changing service day/absence behavior

Fixes the filtering and attendance entry

---

app/services/attendance_csv_importer.rb

business outside of row loop

---

client/src/Dashboard/DashboardStats.js
client/src/Dashboard/DashboardTitle.js
client/src/Dashboard/Notifications.js

minor style tweaks

---

client/src/Dashboard/Dashboard.js
client/src/Dashboard/Notifications.js
client/src/Dashboard/__tests__/Notifications.test.js
client/src/_assets/styles/notification-modal-overrides.css

This PR closes #2631 by creating the modal for the notifications list.

Pie 2631/notifications modal

---

client/src/Dashboard/Notifications.js
client/src/_assets/styles/notification-list-overrides.css
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

add styling tweaks, spanish translation

---

lib/tasks/fix_absences20220614.rake
lib/tasks/fix_absences_2022_06_14.rake
lib/tasks/nebraska_daily_absences.rake

Adds service days to all dates since 2022-06-13 and fixes potential bug in absence generator.

Task to fix absences, fixes bug in the daily rake task

---

client/src/_assets/styles/timepicker-overrides.css
client/src/_shared/AttendanceDataCell.js

change ok text color to black

---

app/services/wonderschool/necc/onboarding_case_importer.rb

Closes #2779 and addresses case in #2778.

PIE-2779/family_fee_not_importing

---

client/src/AttendanceView/AttendanceView.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

#2089 This would add a spanish translation for no check out time(sin hora de salida) on the view attendance page.

Add spanish translation for no check out time

---

client/src/Dashboard/DashboardTable.js
client/src/Dashboard/Notifications.js

adjust link styles

---

app/controllers/application_controller.rb
app/lib/appsignal_reporting.rb
app/lib/aws_client.rb
app/services/attendance_csv_importer.rb
app/services/wonderschool/necc/attendance_csv_importer.rb
app/services/wonderschool/necc/onboarding_case_importer.rb
app/validators/date_param_validator.rb
app/validators/date_time_param_validator.rb
app/validators/time_param_validator.rb
spec/factories/nebraska_approval_amounts.rb
spec/lib/appsignal_reporting_spec.rb
spec/lib/aws_client_spec.rb
spec/services/wonderschool/necc/onboarding_case_importer_spec.rb

Closes #2281 
Closes #1594 
Permanent fix to close #2803
Better error tagging in AppSignal to allow for filtering by tags rather than looking at metadata individually

Error handling improvements

---

app/services/attendance_csv_importer.rb

Updates the attendance importer to have smarter filename handling

---

client/src/Attendance/Attendance.js
client/src/AttendanceView/AttendanceView.js
client/src/_assets/styles/attendance-table-overrides.css

attendance table updates

---

app/mailers/devise_custom_mailer.rb

Bugfix in emails

---

README.md

small updates to readme documentation

---

app/services/wonderschool/necc/onboarding_case_importer.rb

Fix to onboarding case importer

---

client/src/Dashboard/DashboardTable.js

Names are now visible in Illinois Dashboard 

---

client/src/Dashboard/DashboardTable.js
client/src/i18n/locales/en/index.json

Fix to make earned revenue appear

---

client/src/Dashboard/DashboardTable.js

Sets table name font to 16px in IL dashboard

Pie 2852/name font size

---

db/seeds.rb

Fix staging dashboard behavior - cause at risk tags to show.

Modified seed data for Illinois dashboard

---

client/src/Confirmation/Confirmation.js
client/src/Login/Login.js
db/seeds.rb
spec/cypress/integration/confirmation.spec.js
spec/cypress/integration/login.spec.js

Coming soon message removed for IL users

---

client/src/_shared/Header.js

logo now clickable and sends you back to dashboard

---

client/src/Signup/Signup.js
client/src/_shared/_hooks/useFreshsales.js

added hook to add and remove script from head

---

lib/tasks/fix_school_age_rates.rake

Rake to fix school age parameter in recent updated rates and recalculate all potentially affected service days

---

client/src/Signup/Signup.js
client/src/_shared/_hooks/useFreshsales.js

Pie 2905/html tag in signup

---

app/models/concerns/licenses.rb
app/services/illinois_onboarding_case_importer.rb

Updates licenses to include new licenses for illinois onboarding script (#2862 )

Pie 2862/onboarding script update

---

app/blueprints/user_blueprint.rb
app/controllers/api/v1/users_controller.rb
app/models/user.rb
app/services/illinois_onboarding_case_importer.rb

Allows admin IL users to see all IL children. 
Login in as an IL admin to all IL children.

Gives IL admin users permission to view all IL children in database

---

app/models/child.rb
app/services/date_service.rb
app/services/illinois/eligible_days_calculator.rb
db/schema.rb
db/seeds.rb
spec/factories/business_closures.rb
spec/factories/businesses.rb
spec/services/illinois/eligible_days_calculator_spec.rb

This allows to calculate eligible Full Time and Part Time days for Illinois children considering holidays and days that the provider might be closed. 
https://github.com/pieforproviders/pieforproviders/issues/2979
https://github.com/pieforproviders/pieforproviders/issues/2971
https://github.com/pieforproviders/pieforproviders/issues/2923
Make sure you drop your local database, create it again, run migrations and run `bundle exec rails db:setup`
There isn't a clear way to test it until the UI piece is ready.

feat: [P4P-2971, P4P-2979] Calculate FT and PT for IL children

---

app/services/illinois/eligible_days_calculator.rb
app/services/illinois_attendance_rate_calculator.rb
spec/services/illinois/eligible_days_calculator_spec.rb
spec/services/illinois_attendance_rate_calculator_spec.rb

IL onboarding upload without full time and part time caused dashboard to break.

fix: [PIE-2971] Fixing eligible days, ft and pt when days approved not present

---

app/blueprints/child_blueprint.rb
app/models/approval.rb
app/models/business.rb
app/models/child.rb
app/models/illinois/dashboard_case.rb
app/models/service_day.rb
app/services/attendance_rate_calculator.rb
app/services/illinois/business_attendance_rate_calculator.rb
app/services/illinois_attendance_rate_calculator.rb
client/src/Dashboard/Dashboard.js
client/src/_shared/_hooks/useCaseData.js
spec/factories/businesses.rb
spec/services/illinois/business_attendance_rate_calculator_spec.rb
spec/services/illinois_attendance_rate_calculator_spec.rb

Changes for Illinois Attendance Rate given card PIE-2924 criteria. Dashboard attendance rate info small bug fixed.

Pie 2924 Business Attendance Rate Calculator 

---

client/src/Signup/Signup.js
spec/services/illinois/business_attendance_rate_calculator_spec.rb

Freshworks sign-up & status hidden field values updated

[PIE-3053][Martin] Freshworks updates finished

---

client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js

Changes for PIE-2937 card, Merge Illinois dashboard table child name, case number and business columns

[PIE-2937][Martin] Illinois Child name, Case number and Business columns merged

---

app/models/business.rb
app/models/illinois/dashboard_case.rb

Fixed  dashboard Info not showing for IL centers

[TAP-3063][Martin] Dashboard not showing info fixed

---

app/models/business.rb
app/models/illinois/dashboard_case.rb
app/models/illinois_rate.rb
app/services/illinois/earned_revenue_calculator.rb
spec/models/business_spec.rb
spec/models/illinois/dashboard_case_spec.rb

Applies quality rating bump to revenue calculators

Pie 2970 quality rating bump applied to calculated rate

---

app/services/illinois_onboarding_case_importer.rb
spec/services/illinois_onboarding_case_importer_spec.rb

Wrong quality rating on IL onboarding process fixed

[PIE-2970][Martin] Wrong quality rating on IL onboarding process fixed

---

app/models/illinois/dashboard_case.rb
app/services/illinois/daily/revenue_calculator.rb
spec/models/illinois/dashboard_case_spec.rb

Fix Card PIE-3103: Calculates earned revenue for child with special needs

[PIE-3103][Martin] Calculate earned revenue for child with special needs rate finished

---

app/controllers/api/v1/businesses_controller.rb
spec/requests/api/v1/businesses_spec.rb

This will alphabetize the businesses in the filter by site dropdown.  #3131

Pie 3131/alphabetize filter dropdowns

---

client/src/Attendance/Attendance.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

The issue was originated by multiple clicks on the 'save' button when entering attendance manually. I solved the problem disabling the button once it is clicked and enabling it again once the process is finished

[PIE-3148] Saving feedback when entering attendance manually

---

client/src/Dashboard/DashboardTable.js

Fix for date not showing correctly on firefox

[PIE-3136-Fix][Martin] Fix for date not showing correctly on firefox

---

client/src/AttendanceView/AttendanceView.js

Inactive children removed from the attendance view

[PIE-3151][Martin] Inactive children removed from the attendance view

---

client/src/AttendanceView/AttendanceView.js
client/src/_assets/styles/attendance-filters.css
spec/cypress/integration/attendanceView.spec.js

[PIE-3153][Martin] Checkbox to show or hide weekends from attendance view
Checkbox to show or hide weekends from attendance view

[PIE-3153][Martin] Checkbox to show or hide weekends from attendance view

---

client/src/_assets/styles/dashboard-overrides.css
client/src/_assets/styles/select-overrides.css
client/src/_assets/styles/timepicker-overrides.css

Styles fix for ant design upgrade

[PIE-3130][Martin] Styles fix

---

app/services/attendance_csv_importer.rb
app/services/commands/attendance/create.rb
app/services/commands/attendance/update.rb
spec/factories/attendances.rb
spec/services/attendance_csv_importer_spec.rb
spec/services/commands/attendance/create_spec.rb
spec/services/wonderschool/necc/attendance_csv_importer_spec.rb

Fix dashboard showing wrong check in and check out times

Pie 3233 Fix dashboard showing wrong check in and check out times

---

app/controllers/api/v1/service_days_controller.rb
app/models/service_day.rb
client/src/Attendance/Attendance.js
spec/requests/api/v1/service_days_spec.rb
spec/services/illinois_attendance_rate_calculator_spec.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

Fix for duplicated service days with attendance and absence on the same date

Pie 3240 Fix for duplicated service days with attendance and absence on the same date

---

app/models/user.rb
client/src/Dashboard/Dashboard.js

Fix issue with expiration date on children approvals

[PIE-3224][Martin] Fix issue with expiration date on children approvals

---

app/services/attendance_xlsx_importer.rb
app/services/xlsx_attendance_reader.rb

Changes to support attendances without check_out times

Excel importer fix

---

app/models/state.rb
app/models/state_time_rule.rb
db/migrate/20230619163226_create_states.rb
db/migrate/20230619163320_create_state_time_rules.rb
db/schema.rb
db/seeds.rb
lib/tasks/populate_state_time_rule.rake

[PIE-3254][Martin] Time conversion engine models

---

app/services/time_conversion_engine.rb

Service for time conversion engine

[PIE-3255][Martin] time conversion engine service

---

app/services/nebraska/total_time_in_care_calculator.rb
app/services/time_conversion_engine.rb
db/schema.rb
db/seeds.rb
lib/tasks/populate_state_time_rule.rake
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/blueprints/user_blueprint_spec.rb
spec/cypress/integration/attendanceView.spec.js
spec/cypress/integration/casesImport.spec.js
spec/cypress/support/on-rails.js
spec/factories/state_time_rules.rb
spec/factories/states.rb
spec/models/child_spec.rb
spec/models/service_day_spec.rb
spec/requests/api/v1/attendance_batches_spec.rb
spec/requests/api/v1/service_days_spec.rb
spec/services/commands/attendance/create_spec.rb
spec/services/commands/attendance/delete_spec.rb
spec/services/commands/attendance/update_spec.rb
spec/services/nebraska/absence_generator_spec.rb
spec/services/nebraska/daily/days_duration_calculator_spec.rb
spec/services/nebraska/daily/hours_duration_calculator_spec.rb
spec/services/nebraska/tags_calculator_spec.rb
spec/services/nebraska/weekly/attended_hours_calculator_spec.rb

Service day update with new time conversion engine

[PIE-3257][Martin] Service day update with new time conversion engine

---

app/models/child_approval.rb
app/services/wonderschool/necc/onboarding_case_importer.rb
db/migrate/20230704230941_add_part_days_to_child_approvals.rb
db/schema.rb
spec/factories/child_approvals.rb
spec/models/child_approval_spec.rb

https://github.com/pieforproviders/pieforproviders/issues/3266
Try uploading a CSV file with the two new columns.

feat: [PIE-3266] [Fabian] Adding part days and part days special rate to onboarding process for NE

---

app/blueprints/nebraska/dashboard_case_blueprint.rb
app/models/child_approval.rb
app/models/nebraska/dashboard_case.rb
app/services/nebraska/eligible_days_calculator.rb
client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/_shared/_hooks/useCaseData.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
db/schema.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb

Pie 3248 Dashboard update with new Nebraska rules

---

app/lib/aws_client.rb
app/services/attendance_csv_importer.rb
app/services/attendance_pdf_importer.rb
app/services/commands/attendance/parse_pdf.rb
app/services/time_conversion_engine.rb
spec/services/attendance_csv_importer_spec.rb

Pie 3279 Fixes for issues with XLSX, CSV and PDF importers

---

app/blueprints/service_day_blueprint.rb
client/src/AttendanceView/AttendanceView.js
spec/blueprints/service_day_blueprint_spec.rb

[nostory][Martin] replace part day tag with partial day

---

lib/tasks/update_service_days_rules.rake

Update nebraska service days with new rules tasks

---

app/models/nebraska/dashboard_case.rb
app/services/nebraska/daily/days_duration_calculator.rb

* [X ] Did you write & run tests and linters?

[PIE-3300][Martin] Full days calculations fixed

---

client/src/Attendance/Attendance.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json

[PIE-3295][Martin] Go to dashboard button changed for View attendance

---

app/blueprints/nebraska/dashboard_case_blueprint.rb
app/models/nebraska/dashboard_case.rb
client/src/AttendanceView/AttendanceView.js
client/src/Dashboard/DashboardTable.js
client/src/Dashboard/__tests__/DashboardTable.test.js
client/src/_shared/_hooks/useCaseData.js
client/src/i18n/locales/en/index.json
client/src/i18n/locales/es/index.json
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/models/child_spec.rb
spec/services/commands/attendance/create_spec.rb
spec/services/commands/attendance/update_spec.rb

[PIE-3306][Martin] Remaining dashboard updates for Nebraska new rules

---

app/services/wonderschool/necc/onboarding_case_importer.rb

Pie 3294 Fix for case sensitive child's names

---

app/services/nebraska/absence_generator.rb

[PIE-3269][Martin] Fix for absence and attendance saving on the same day

---

lib/tasks/remove_duplicate_absences_entries.rake

[nostory][Martin] use date argument on remove_absences task

---

app/services/attendance_csv_importer.rb
app/services/attendance_pdf_importer.rb
app/services/attendance_xlsx_importer.rb
app/services/name_matching_actions.rb
app/services/name_matching_engine.rb

Pie 3325 update

---

app/services/attendance_csv_importer.rb
app/services/name_matching_actions.rb
app/services/name_matching_engine.rb
spec/services/attendance_csv_importer_spec.rb

[PIE-3325][Martin] Remove unnecesary messages

---

client/src/Attendance/Attendance.js

[nostory][Martin] Fix for excessive memory usage on Attendance edit page

---

app/models/child.rb

[PIE-3394][Martin] fix for nebraska absences generator

---

app/controllers/sessions_controller.rb
client/src/_shared/Header.js
package.json

[PIE-3396][Martin] Fix for logout working incorrectly

---

client/src/Dashboard/Dashboard.js
spec/models/nebraska/dashboard_case_spec.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

[PIE-3406][Martin] fix for issue with date picker on dashboard

---

app/blueprints/nebraska/dashboard_case_blueprint.rb
app/controllers/api/v1/dashboard_case_controller.rb
app/models/nebraska/dashboard_case.rb
client/src/Dashboard/Dashboard.js
client/src/Dashboard/DashboardTable.js
client/src/_shared/_hooks/useAdminData.js
client/src/_shared/_hooks/useCaseDataNew.js
config/routes.rb
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

This change consist on bringing the dashboard information as a unique query against database where it builds all the values that the dashboard needs to show.  Currently this change only applies to Admin users.

[PIE-3409][New dashboard sql service]

---

app/controllers/api/v1/dashboard_case_controller.rb

Fix for the new dashboard query, it was not working when selecting multiple businesses on the filter

Fix for business filter with new dashbard query

---

app/models/nebraska/dashboard_case.rb
client/src/Dashboard/DashboardTable.js

Max hours failing after the new dashboard update fixed.

fix for max hours filter on the dashboard

---

app/controllers/api/v1/dashboard_case_controller.rb

Update dashboard query

---

app/services/attendance_csv_importer.rb
app/services/name_matching_actions.rb
app/services/name_matching_engine.rb
spec/services/name_matching_engine_spec.rb

Name Matching engine failing when finding more than one match

Upgrade on name matching engine 

---

app/services/name_matching_actions.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

Fix on attendance csv uploader

---

app/models/approval.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

Fix for attendances being saved prior authorization period start date

---

app/services/attendance_csv_importer.rb
app/services/name_matching_actions.rb
spec/services/attendance_csv_importer_spec.rb

Upload many children attendances on a single csv

---

app/blueprints/child_blueprint.rb
app/controllers/api/v1/attendance_view_controller.rb
app/services/attendance_info_service.rb
client/src/AttendanceView/AttendanceView.js
client/src/AttendanceView/_tests_/AttendanceView.test.js
config/routes.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

Update attendance view service for performance improvement

---

app/controllers/api/v1/attendance_view_controller.rb
client/src/_shared/SiteFilterSelect.js

Fix for businesses filter on attendance view

Fix for businesses filter on attendance view

---

app/services/attendance_pdf_importer.rb
spec/services/illinois_attendance_risk_calculator_spec.rb

attendance pdf importer not working

[EC-288] Attendance pdf importer not working

---

app/services/attendance_pdf_importer.rb
app/services/commands/attendance/parse_pdf.rb

PDF uploader not working on blank check_in/check_out info
* [ X] Did you write & run tests and linters?

[Freshdesk ticket 8288 ] PDF uploader not working on blank check_in/check_out info

---

client/src/AttendanceView/AttendanceView.js

[EC-289] Update attendance button not working

---

lib/tasks/remove_not_attending_period_absences.rake
spec/blueprints/nebraska/dashboard_case_blueprint_spec.rb

Rake task to remove not attending period absences

Nostory / Rake task to remove not attending period absences

---

package.json

[nostory] Remove NPM from package

---

client/src/Login/Login.js
spec/models/nebraska/dashboard_case_spec.rb

This PR removes the sign-up link on the login page.

[EC-451] Remove sign-up link on login page
